version: '3.4'

services:
  stakehoundbackend:
    image: stakehoundbackend-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./.env:/usr/src/app/.env
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
      - ./state_logs:/usr/src/app/state_logs
      - ./node_modules:/usr/src/app/node_modules
      - ./build:/usr/src/app/build
      - ./mnt:/usr/src/app/mnt
    environment:
      NODE_PATH: /usr/src/app/build
      NODE_ENV: development
    ports:
      - 9229:9229